name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd demo-app
            git pull origin main
            npm install
            pm2 restart app
          EOF
